#!/usr/bin/env bash
set -euxo pipefail

# Copy Apache Fineract JAR
mkdir -p build/run
cp fineract/fineract-provider/build/libs/fineract-provider*.jar build/run

# Add our fineract-pentaho reporting plugin, like so:
unzip fineract-pentaho/build/distributions/fineract-pentaho.zip -d build/run/
rm build/run/fineract-pentaho.jar

mkdir -p ~/.mifosx/pentahoReports/
cp build/run/pentahoReports/* ~/.mifosx/pentahoReports/
rm -rf build/run/pentahoReports

# Start!
java -Dloader.path=build/run/lib/ -jar build/run/fineract-provider.jar
